### ISSUE TITLE
Discover Device empty

### ISSUE THREAD

**Issue by eagnoor** [ume05rw/SharpBroadlink#1]
The RM PRO connects to WiFi correctly because the blue led stops blinking, but the devices list is empty, I tried to increase the time but i'm getting a null anyways.

await Broadlink.Setup("xxx", "xxx", Broadlink.WifiSecurityMode.WPA2);
var devices = await Broadlink.Discover(30);
var device = (SharpBroadlink.Devices.Rm2Pro)devices.First(d => d.DeviceType == DeviceType.Rm2Pro);

**Comment by ume05rw** [comment]
H, karbu96!
Thank you for using.

Are you running Broadlink.Discover () immediately after Broadlink.Setup ()?

Without giving a little time after Setup (), the device side process can not make it in time.
After waiting for about 5 seconds, the device will respond.

Also, Broadlink.Setup () should only be executed once at device initialization / reset.

**Comment by eagnoor** [comment]
Thanks!
